Module_9.1.3_Outlier.ipynb

In [ ]:
import pandas as pd
import numpy as np

# Sample DataFrame with outliers
data = {'A': [1, 2, 3, 4, 5, 100]}
df = pd.DataFrame(data)

# Calculate Z-score for each data point in column 'A'
z_scores = np.abs((df['A'] - df['A'].mean()) / df['A'].std())

# Define threshold for outlier detection (e.g., Z-score > 3)
threshold = 3
outliers = df[z_scores > threshold]

print("Outliers:")
print(outliers)

Outliers:
Empty DataFrame
Columns: [A]
Index: []

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering',
                              'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})
display('df1', 'df2')

'df1'

'df2'

In [ ]:
df3 = pd.merge(df1, df2)
df3

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [ ]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})
display('df3', 'df4', 'pd.merge(df3, df4)')

'df3'

'df4'

'pd.merge(df3, df4)'

In [ ]:
df5 = pd.DataFrame({'group': ['Accounting', 'Accounting',
                              'Engineering', 'Engineering', 'HR', 'HR'],
                    'skills': ['math', 'spreadsheets', 'software', 'math',
                               'spreadsheets', 'organization']})
display('df1', 'df5', "pd.merge(df1, df5)")

'df1'

'df5'

'pd.merge(df1, df5)'

In [ ]:
display('df1', 'df2', "pd.merge(df1, df2, on='employee')")

'df1'

'df2'

"pd.merge(df1, df2, on='employee')"

In [ ]:
df3 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'salary': [70000, 80000, 120000, 90000]})
display('df1', 'df3', 'pd.merge(df1, df3, left_on="employee", right_on="name")')

'df1'

'df3'

'pd.merge(df1, df3, left_on="employee", right_on="name")'

In [ ]:
pd.merge(df1, df3, left_on="employee", right_on="name").drop('name', axis=1)

  employee        group  salary
0      Bob   Accounting   70000
1     Jake  Engineering   80000
2     Lisa  Engineering  120000
3      Sue           HR   90000

In [ ]:
df1a = df1.set_index('employee')
df2a = df2.set_index('employee')
display('df1a', 'df2a')

'df1a'

'df2a'

In [ ]:

display('df1a', 'df2a',
        "pd.merge(df1a, df2a, left_index=True, right_index=True)")

'df1a'

'df2a'

'pd.merge(df1a, df2a, left_index=True, right_index=True)'

In [ ]:
df1a.join(df2a)

                group  hire_date
employee
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014

In [ ]:
display('df1a', 'df3', "pd.merge(df1a, df3, left_index=True, right_on='name')")

'df1a'

'df3'

"pd.merge(df1a, df3, left_index=True, right_on='name')"

In [ ]:

df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
                    'food': ['fish', 'beans', 'bread']},
                   columns=['name', 'food'])
df7 = pd.DataFrame({'name': ['Mary', 'Joseph'],
                    'drink': ['wine', 'beer']},
                   columns=['name', 'drink'])
display('df6', 'df7', 'pd.merge(df6, df7)')

'df6'

'df7'

'pd.merge(df6, df7)'

In [ ]:
pd.merge(df6, df7, how='inner')

   name   food drink
0  Mary  bread  wine

In [ ]:
display('df6', 'df7', "pd.merge(df6, df7, how='outer')")

'df6'

'df7'

"pd.merge(df6, df7, how='outer')"

In [ ]:
display('df6', 'df7', "pd.merge(df6, df7, how='left')")

'df6'

'df7'

"pd.merge(df6, df7, how='left')"

In [ ]:
df8 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'rank': [1, 2, 3, 4]})
df9 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'rank': [3, 1, 4, 2]})
display('df8', 'df9', 'pd.merge(df8, df9, on="name")')

'df8'

'df9'

'pd.merge(df8, df9, on="name")'

In [ ]:
pd.merge(df8, df9, on="name", suffixes=["_L", "_R"])

   name  rank_L  rank_R
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2

Module_9.11.Grouping and Aggregating Data.ipynb

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.rand(5))
ser

0    0.374540
1    0.950714
2    0.731994
3    0.598658
4    0.156019
dtype: float64

In [ ]:
ser.sum()

np.float64(2.811925491708157)

In [ ]:

ser.mean()

np.float64(0.5623850983416314)

In [ ]:
df = pd.DataFrame({'A': rng.rand(5),
                   'B': rng.rand(5)})
df

          A         B
0  0.155995  0.020584
1  0.058084  0.969910
2  0.866176  0.832443
3  0.601115  0.212339
4  0.708073  0.181825

In [ ]:

df.mean()

A    0.477888
B    0.443420
dtype: float64

In [ ]:
df.mean(axis='columns')

0    0.088290
1    0.513997
2    0.849309
3    0.406727
4    0.444949
dtype: float64

In [ ]:
import numpy as np
import pandas as pd
rng = np.random.RandomState(42)
ser = pd.Series(rng.rand(5))
ser

0    0.374540
1    0.950714
2    0.731994
3    0.598658
4    0.156019
dtype: float64

In [ ]:

ser.sum()

np.float64(2.811925491708157)

In [ ]:

ser.mean()

np.float64(0.5623850983416314)

In [ ]:
df = pd.DataFrame({'A': rng.rand(5),
                   'B': rng.rand(5)})
df

          A         B
0  0.155995  0.020584
1  0.058084  0.969910
2  0.866176  0.832443
3  0.601115  0.212339
4  0.708073  0.181825

In [ ]:
df.mean()

A    0.477888
B    0.443420
dtype: float64

In [ ]:
df.mean(axis='columns')

0    0.088290
1    0.513997
2    0.849309
3    0.406727
4    0.444949
dtype: float64

In [ ]:
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'data': range(6)}, columns=['key', 'data'])
df

  key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [ ]:
df.groupby('key')

In [ ]:

df.groupby('key').sum()

     data
key
A       3
B       5
C       7

In [ ]:
rng = np.random.RandomState(0)
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'data1': range(6),
                   'data2': rng.randint(0, 10, 6)},
                   columns = ['key', 'data1', 'data2'])
df

  key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9

In [ ]:
df.groupby('key').aggregate(['min', np.median, max])

    data1            data2
      min median max   min median max
key
A       0    1.5   3     3    4.0   5
B       1    2.5   4     0    3.5   7
C       2    3.5   5     3    6.0   9

In [ ]:
df.groupby('key').aggregate({'data1': 'min',
                             'data2': 'max'})

     data1  data2
key
A        0      5
B        1      7
C        2      9

In [ ]:

def center(x):
    return x - x.mean()
df.groupby('key').transform(center)

   data1  data2
0   -1.5    1.0
1   -1.5   -3.5
2   -1.5   -3.0
3    1.5   -1.0
4    1.5    3.5
5    1.5    3.0

In [ ]:
L = [0, 1, 0, 1, 2, 0]
df.groupby(L).sum()

   key  data1  data2
0  ACC      7     17
1   BA      4      3
2    B      4      7

In [ ]:
df.groupby(df['key']).sum()

     data1  data2
key
A        3      8
B        5      7
C        7     12

In [ ]:
df2 = df.set_index('key')
mapping = {'A': 'vowel', 'B': 'consonant', 'C': 'consonant'}
display('df2', 'df2.groupby(mapping).sum()')

'df2'

'df2.groupby(mapping).sum()'

In [ ]:
df2.groupby([str.lower, mapping]).mean()

               data1  data2
key key
a   vowel        1.5    4.0
b   consonant    2.5    3.5
c   consonant    3.5    6.0

In [ ]:
L = [0, 1, 0, 1, 2, 0]
df.groupby(L).sum()

   key  data1  data2
0  ACC      7     17
1   BA      4      3
2    B      4      7

In [ ]:
df.groupby(df['key']).sum()

     data1  data2
key
A        3      8
B        5      7
C        7     12

In [ ]:
df2 = df.set_index('key')
mapping = {'A': 'vowel', 'B': 'consonant', 'C': 'consonant'}
display('df2', 'df2.groupby(mapping).sum()')

'df2'

'df2.groupby(mapping).sum()'

In [ ]:
df2.groupby([str.lower, mapping]).mean()

               data1  data2
key key
a   vowel        1.5    4.0
b   consonant    2.5    3.5
c   consonant    3.5    6.0

Module_9.1_handling_missing_data.ipynb

In [11]:
import pandas as pd

# Create a DataFrame with missing values
data = {'A': [1, 2, None, 4],
        'B': [5, None, 7, 8]}
df = pd.DataFrame(data)

# Drop rows with missing values
df_dropped = df.dropna()

# Fill missing values with mean
df_filled = df.fillna(df.mean())

print("Original DataFrame:")
print(df)
print("\nDataFrame after dropping missing values:")
print(df_dropped)
print("\nDataFrame after filling missing values:")
print(df_filled)

Original DataFrame:
     A    B
0  1.0  5.0
1  2.0  NaN
2  NaN  7.0
3  4.0  8.0

DataFrame after dropping missing values:
     A    B
0  1.0  5.0
3  4.0  8.0

DataFrame after filling missing values:
          A         B
0  1.000000  5.000000
1  2.000000  6.666667
2  2.333333  7.000000
3  4.000000  8.000000

In [ ]:
Module_9.2_Numpy_Series_Object.ipynb

In [12]:
import numpy as np
import pandas as pd

In [13]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [14]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [15]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: str

In [16]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[1, 2])

1    b
2    a
dtype: str

Module_9.3_Pandas_Series.ipynb

In [17]:
# import pandas as pd
import pandas as pd

# simple array
data = [1, 2, 3, 4]

ser = pd.Series(data)
print(ser)

0    1
1    2
2    3
3    4
dtype: int64

In [18]:
area_dict = {'California': 423967, 'Texas': 695662, 'Florida': 170312,
             'New York': 141297, 'Pennsylvania': 119280}
area = pd.Series(area_dict)
area

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
dtype: int64

In [19]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

     a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

Module_9.5_Model_Selection.ipynb

In [21]:
import numpy as np
import pandas as pd


index = [('California', 2010), ('California', 2020),
         ('New York', 2010), ('New York', 2020),
         ('Texas', 2010), ('Texas', 2020)]
populations = [37253956, 39538223,
               19378102, 20201249,
               25145561, 29145505]
pop = pd.Series(populations, index=index)
pop

(California, 2010)    37253956
(California, 2020)    39538223
(New York, 2010)      19378102
(New York, 2020)      20201249
(Texas, 2010)         25145561
(Texas, 2020)         29145505
dtype: int64

In [22]:
pop[('California', 2020):('Texas', 2010)]

(California, 2020)    39538223
(New York, 2010)      19378102
(New York, 2020)      20201249
(Texas, 2010)         25145561
dtype: int64

In [23]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex([('California', 2010),
            ('California', 2020),
            (  'New York', 2010),
            (  'New York', 2020),
            (     'Texas', 2010),
            (     'Texas', 2020)],
           )

In [24]:
pop = pop.reindex(index)
pop

California  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
Texas       2010    25145561
            2020    29145505
dtype: int64

In [25]:

df = pd.DataFrame(np.random.rand(4, 2),
                  index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                  columns=['data1', 'data2'])
df

        data1     data2
a 1  0.446568  0.598741
  2  0.814994  0.453541
b 1  0.818673  0.350879
  2  0.785130  0.230669

Module_9.6_Dropping Level, Transposing_.ipynb

In [26]:
import numpy as np
import pandas as pd

In [27]:
import pandas as pd

# Sample DataFrame with MultiIndex
arrays = [['A', 'A', 'B', 'B'], [1, 2, 1, 2]]
tuples = list(zip(*arrays))
index = pd.MultiIndex.from_tuples(tuples, names=['first', 'second'])
df = pd.DataFrame({'data': [1, 2, 3, 4]}, index=index)

print(df)

              data
first second
A     1          1
      2          2
B     1          3
      2          4

In [28]:
# Drop levels from MultiIndex
df_dropped = df.droplevel('first')

print(df_dropped)

        data
second
1          1
2          2
1          3
2          4

Module_9.7_Accessing Rows, Adding and Removing Columns.ipynb

In [29]:
import pandas as pd
import numpy as np

# URL of the dataset
url = "https://storage.googleapis.com/download.tensorflow.org/data/iris_training.csv"

# Load the dataset into a DataFrame
df = pd.read_csv(url)

# Display the original DataFrame
print("Original DataFrame:")
print(df.head())  # Display the first few rows
print()

# Adding a new column
new_col = np.random.randint(100, size=len(df))
df.insert(3, 'new_col2', new_col)  # Example values

# Display the DataFrame after adding the new column
print("DataFrame after adding 'New_Column':")
print(df.head())  # Display the first few rows
print()

# Accessing rows
print("Accessing rows:")
print(df.iloc[0])  # Access the first row
print(df.iloc[1:3])  # Access rows from index 1 to 2
print()

# Removing a column
df.drop(columns=['setosa'], inplace=True)  # Specify the column to delete

# Display the DataFrame after removing the specified column
print("DataFrame after removing 'Column_To_Delete':")
print(df.head())  # Display the first few rows

Original DataFrame:
   120    4  setosa  versicolor  virginica
0  6.4  2.8     5.6         2.2          2
1  5.0  2.3     3.3         1.0          1
2  4.9  2.5     4.5         1.7          2
3  4.9  3.1     1.5         0.1          0
4  5.7  3.8     1.7         0.3          0

DataFrame after adding 'New_Column':
   120    4  setosa  new_col2  versicolor  virginica
0  6.4  2.8     5.6        16         2.2          2
1  5.0  2.3     3.3        41         1.0          1
2  4.9  2.5     4.5        86         1.7          2
3  4.9  3.1     1.5        52         0.1          0
4  5.7  3.8     1.7        85         0.3          0

Accessing rows:
120            6.4
4              2.8
setosa         5.6
new_col2      16.0
versicolor     2.2
virginica      2.0
Name: 0, dtype: float64
   120    4  setosa  new_col2  versicolor  virginica
1  5.0  2.3     3.3        41         1.0          1
2  4.9  2.5     4.5        86         1.7          2

DataFrame after removing 'Column_To_Delete':
   120    4  new_col2  versicolor  virginica
0  6.4  2.8        16         2.2          2
1  5.0  2.3        41         1.0          1
2  4.9  2.5        86         1.7          2
3  4.9  3.1        52         0.1          0
4  5.7  3.8        85         0.3          0

Module_9.8 Querying and Sorting DataFrame_.ipynb

In [30]:
# import pandas library as pd
import pandas as pd

# List of Tuples
students = [('Ankit', 22, 'Up', 'Geu'),
           ('Ankita', 31, 'Delhi', 'Gehu'),
           ('Rahul', 16, 'Tokyo', 'Abes'),
           ('Simran', 41, 'Delhi', 'Gehu'),
           ('Shaurya', 33, 'Delhi', 'Geu'),
           ('Harshita', 35, 'Mumbai', 'Bhu' ),
           ('Swapnil', 35, 'Mp', 'Geu'),
           ('Priya', 35, 'Uk', 'Geu'),
           ('Jeet', 35, 'Guj', 'Gehu'),
           ('Ananya', 35, 'Up', 'Bhu')
            ]

# Create a DataFrame object from
# list of tuples with columns
# and indices.
details = pd.DataFrame(students, columns =['Name', 'Age',
                                           'Place', 'College'],
                        index =[ 'b', 'c', 'a', 'e', 'f',
                                'g', 'i', 'j', 'k', 'd'])

# Sort the rows of dataframe by 'Name' column
rslt_df = details.sort_values(by = 'Name')

# show the resultant Dataframe
rslt_df

       Name  Age   Place College
d    Ananya   35      Up     Bhu
b     Ankit   22      Up     Geu
c    Ankita   31   Delhi    Gehu
g  Harshita   35  Mumbai     Bhu
k      Jeet   35     Guj    Gehu
j     Priya   35      Uk     Geu
a     Rahul   16   Tokyo    Abes
f   Shaurya   33   Delhi     Geu
e    Simran   41   Delhi    Gehu
i   Swapnil   35      Mp     Geu

Module_9.9 Operations on DataFrame.ipynb

In [31]:
import pandas as pd

df = pd.DataFrame({
    'name': ['alice','bob','charlie'],
    'age': [25,26,27]
})

df.rename(columns={'name':'person_name'})

  person_name  age
0       alice   25
1         bob   26
2     charlie   27

In [32]:
import pandas as pd

df = pd.DataFrame({
    'name': ['alice','bob','charlie'],
    'age': [25,26,27]
})

df.rename(columns={'name':'person_name','age':'age_in_years'})

  person_name  age_in_years
0       alice            25
1         bob            26
2     charlie            27

In [33]:
import numpy as np
df = pd.DataFrame({
    'name': ['alice','bob','charlie'],
    'age': [25,26,np.nan],
    'state': ['ak',np.nan,None]
})

print(df['name'].isnull().sum())

print(df['age'].isnull().sum())

print(df['state'].isnull().sum())

0
1
2